services:
  - type: web
    name: dhan-auto-exit-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    pythonVersion: 3.10
